###########################
# Configuration for rubocop
# in .rubocop.yml 
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

StringLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/Documentation:
  Enabled: false
